---
- name: wait for ssh connection
  hosts: all
  gather_facts: False
  tasks: 
   - name: ensure ssh port open
     wait_for: 
      port: 22
      delay: 10
      timeout: 100
      search_regex: OpenSSH
      host: '{{ (ansible_ssh_host|default(ansible_host))|default(inventory_hostname) }}'
     vars: 
      ansible_connection: local
      ansible_python_interpreter: /usr/bin/python 
      
- name: install python3 and docker on ec2 instance
  hosts: all
  become: yes
  gather_facts: False
  tasks:
    - name: update yum cache
      yum:
        name: '*'
        state: latest
        update_cache: yes
    - name: install python3 and docker
      vars: 
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
         - python3
         - docker
        update_cache: yes
        state: present
    - name: install docker python module
      pip:
       name: docker
    - name: start docker daemon
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: add ec2-user to docker group
      user: 
       name: ec2-user
       groups: docker
       append: yes
    - name: reconnect to server session
      meta: reset_connection 
    
- name: install docker compose
  hosts: all
  tasks:
    - name: install docker compose
      get_url:
        url: "https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64"
        dest: /usr/local/bin/docker-compose
        mode: +x
    - name: add docker compose symbolic link
      file:
        src: /usr/local/bin/docker-compose
        dest: /usr/bin/docker-compose
        state: link
    - name: install compose python module
      pip: 
        name: docker-compose

- name: start docker containers
  hosts: all
  vars_files:
    - project-vars
  tasks: 
    - name: copy docker compose from local machine
      copy:
        src: []
        dest: /home/ec2-user/docker-compose.yml
    - name: docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: tomiwa97
        password: "{{docker_password}}"
    - name: start containers from compose
      docker_compose:
        project_src: /home/ec2-user